LogDir = "/conf/data"
LogLevel = "DEBUG"

[Rpc.gor]
  Url = "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
[Rpc.rin]
  Url = "https://rinkeby.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
[Rpc.kov]
  Url = "https://kovan.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
