global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: meson-server
    static_configs:
      - targets: [mix1:6543]
      - targets: [mix2:6543]
      - targets: [mix3:6543]
      - targets: [provider1:6543]
      - targets: [provider2:6543]
  - job_name: katzenmint
    static_configs:
      - targets: [auth1:26660]
      - targets: [auth2:26660]
      - targets: [auth3:26660]
      - targets: [auth4:26660]