---
- name: Prepare repo key
  apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Prepare repository
  apt_repository:
  repo: deb https://packages.grafana.com/oss/deb stable main

- name: Install packages
  apt:
    name:
      - prometheus
      - grafana

- name: Copy prometheus config
  template:
    src: prometheus.yaml.j2
    dest: /etc/prometheus/prometheus.yml
